export const mapping = {
	U: {
		clockwise: [
			[{ face: 'U', index: 0 }, { face: 'U', index: 6 }],
			[{ face: 'U', index: 1 }, { face: 'U', index: 3 }],
			[{ face: 'U', index: 2 }, { face: 'U', index: 0 }],
			[{ face: 'U', index: 3 }, { face: 'U', index: 7 }],
			[{ face: 'U', index: 5 }, { face: 'U', index: 1 }],
			[{ face: 'U', index: 6 }, { face: 'U', index: 8 }],
			[{ face: 'U', index: 7 }, { face: 'U', index: 5 }],
			[{ face: 'U', index: 8 }, { face: 'U', index: 2 }],
			[{ face: 'F', index: 0 }, { face: 'R', index: 0 }],
			[{ face: 'F', index: 1 }, { face: 'R', index: 1 }],
			[{ face: 'F', index: 2 }, { face: 'R', index: 2 }],
			[{ face: 'R', index: 0 }, { face: 'B', index: 0 }],
			[{ face: 'R', index: 1 }, { face: 'B', index: 1 }],
			[{ face: 'R', index: 2 }, { face: 'B', index: 2 }],
			[{ face: 'B', index: 0 }, { face: 'L', index: 0 }],
			[{ face: 'B', index: 1 }, { face: 'L', index: 1 }],
			[{ face: 'B', index: 2 }, { face: 'L', index: 2 }],
			[{ face: 'L', index: 0 }, { face: 'F', index: 0 }],
			[{ face: 'L', index: 1 }, { face: 'F', index: 1 }],
			[{ face: 'L', index: 2 }, { face: 'F', index: 2 }]
		],
		counterClockwise: [
			[{ face: 'U', index: 0 }, { face: 'U', index: 2 }],
			[{ face: 'U', index: 1 }, { face: 'U', index: 5 }],
			[{ face: 'U', index: 2 }, { face: 'U', index: 8 }],
			[{ face: 'U', index: 3 }, { face: 'U', index: 1 }],
			[{ face: 'U', index: 5 }, { face: 'U', index: 7 }],
			[{ face: 'U', index: 6 }, { face: 'U', index: 0 }],
			[{ face: 'U', index: 7 }, { face: 'U', index: 3 }],
			[{ face: 'U', index: 8 }, { face: 'U', index: 6 }],
			[{ face: 'F', index: 0 }, { face: 'L', index: 0 }],
			[{ face: 'F', index: 1 }, { face: 'L', index: 1 }],
			[{ face: 'F', index: 2 }, { face: 'L', index: 2 }],
			[{ face: 'L', index: 0 }, { face: 'B', index: 0 }],
			[{ face: 'L', index: 1 }, { face: 'B', index: 1 }],
			[{ face: 'L', index: 2 }, { face: 'B', index: 2 }],
			[{ face: 'B', index: 0 }, { face: 'R', index: 0 }],
			[{ face: 'B', index: 1 }, { face: 'R', index: 1 }],
			[{ face: 'B', index: 2 }, { face: 'R', index: 2 }],
			[{ face: 'R', index: 0 }, { face: 'F', index: 0 }],
			[{ face: 'R', index: 1 }, { face: 'F', index: 1 }],
			[{ face: 'R', index: 2 }, { face: 'F', index: 2 }]
		]
	},
	F: {
		clockwise: [
			[{ face: 'F', index: 0 }, { face: 'F', index: 6 }],
			[{ face: 'F', index: 1 }, { face: 'F', index: 3 }],
			[{ face: 'F', index: 2 }, { face: 'F', index: 0 }],
			[{ face: 'F', index: 3 }, { face: 'F', index: 7 }],
			[{ face: 'F', index: 5 }, { face: 'F', index: 1 }],
			[{ face: 'F', index: 6 }, { face: 'F', index: 8 }],
			[{ face: 'F', index: 7 }, { face: 'F', index: 5 }],
			[{ face: 'F', index: 8 }, { face: 'F', index: 2 }],
			[{ face: 'U', index: 6 }, { face: 'R', index: 0 }],
			[{ face: 'U', index: 7 }, { face: 'R', index: 3 }],
			[{ face: 'U', index: 8 }, { face: 'R', index: 6 }],
			[{ face: 'R', index: 0 }, { face: 'D', index: 2 }],
			[{ face: 'R', index: 3 }, { face: 'D', index: 1 }],
			[{ face: 'R', index: 6 }, { face: 'D', index: 0 }],
			[{ face: 'D', index: 0 }, { face: 'L', index: 2 }],
			[{ face: 'D', index: 1 }, { face: 'L', index: 5 }],
			[{ face: 'D', index: 2 }, { face: 'L', index: 8 }],
			[{ face: 'L', index: 2 }, { face: 'U', index: 6 }],
			[{ face: 'L', index: 5 }, { face: 'U', index: 7 }],
			[{ face: 'L', index: 8 }, { face: 'U', index: 8 }]
		],
		counterClockwise: [
			[{ face: 'F', index: 0 }, { face: 'F', index: 2 }],
			[{ face: 'F', index: 1 }, { face: 'F', index: 5 }],
			[{ face: 'F', index: 2 }, { face: 'F', index: 8 }],
			[{ face: 'F', index: 3 }, { face: 'F', index: 1 }],
			[{ face: 'F', index: 5 }, { face: 'F', index: 7 }],
			[{ face: 'F', index: 6 }, { face: 'F', index: 0 }],
			[{ face: 'F', index: 7 }, { face: 'F', index: 3 }],
			[{ face: 'F', index: 8 }, { face: 'F', index: 6 }],
			[{ face: 'U', index: 6 }, { face: 'L', index: 2 }],
			[{ face: 'U', index: 7 }, { face: 'L', index: 5 }],
			[{ face: 'U', index: 8 }, { face: 'L', index: 8 }],
			[{ face: 'L', index: 2 }, { face: 'D', index: 0 }],
			[{ face: 'L', index: 5 }, { face: 'D', index: 1 }],
			[{ face: 'L', index: 8 }, { face: 'D', index: 2 }],
			[{ face: 'D', index: 0 }, { face: 'R', index: 6 }],
			[{ face: 'D', index: 1 }, { face: 'R', index: 3 }],
			[{ face: 'D', index: 2 }, { face: 'R', index: 0 }],
			[{ face: 'R', index: 0 }, { face: 'U', index: 6 }],
			[{ face: 'R', index: 3 }, { face: 'U', index: 7 }],
			[{ face: 'R', index: 6 }, { face: 'U', index: 8 }]
		]
	},

	D: {
		clockwise: [
			[{ face: 'D', index: 0 }, { face: 'D', index: 6 }],
			[{ face: 'D', index: 1 }, { face: 'D', index: 3 }],
			[{ face: 'D', index: 2 }, { face: 'D', index: 0 }],
			[{ face: 'D', index: 3 }, { face: 'D', index: 7 }],
			[{ face: 'D', index: 5 }, { face: 'D', index: 1 }],
			[{ face: 'D', index: 6 }, { face: 'D', index: 8 }],
			[{ face: 'D', index: 7 }, { face: 'D', index: 5 }],
			[{ face: 'D', index: 8 }, { face: 'D', index: 2 }],
			[{ face: 'F', index: 6 }, { face: 'L', index: 6 }],
			[{ face: 'F', index: 7 }, { face: 'L', index: 7 }],
			[{ face: 'F', index: 8 }, { face: 'L', index: 8 }],
			[{ face: 'L', index: 6 }, { face: 'B', index: 6 }],
			[{ face: 'L', index: 7 }, { face: 'B', index: 7 }],
			[{ face: 'L', index: 8 }, { face: 'B', index: 8 }],
			[{ face: 'B', index: 6 }, { face: 'R', index: 6 }],
			[{ face: 'B', index: 7 }, { face: 'R', index: 7 }],
			[{ face: 'B', index: 8 }, { face: 'R', index: 8 }],
			[{ face: 'R', index: 6 }, { face: 'F', index: 6 }],
			[{ face: 'R', index: 7 }, { face: 'F', index: 7 }],
			[{ face: 'R', index: 8 }, { face: 'F', index: 8 }]
		],

		counterClockwise: [
			[{ face: 'D', index: 0 }, { face: 'D', index: 2 }],
			[{ face: 'D', index: 1 }, { face: 'D', index: 5 }],
			[{ face: 'D', index: 2 }, { face: 'D', index: 8 }],
			[{ face: 'D', index: 3 }, { face: 'D', index: 1 }],
			[{ face: 'D', index: 5 }, { face: 'D', index: 7 }],
			[{ face: 'D', index: 6 }, { face: 'D', index: 0 }],
			[{ face: 'D', index: 7 }, { face: 'D', index: 3 }],
			[{ face: 'D', index: 8 }, { face: 'D', index: 6 }],
			[{ face: 'F', index: 6 }, { face: 'R', index: 6 }],
			[{ face: 'F', index: 7 }, { face: 'R', index: 7 }],
			[{ face: 'F', index: 8 }, { face: 'R', index: 8 }],
			[{ face: 'R', index: 6 }, { face: 'B', index: 6 }],
			[{ face: 'R', index: 7 }, { face: 'B', index: 7 }],
			[{ face: 'R', index: 8 }, { face: 'B', index: 8 }],
			[{ face: 'B', index: 6 }, { face: 'L', index: 6 }],
			[{ face: 'B', index: 7 }, { face: 'L', index: 7 }],
			[{ face: 'B', index: 8 }, { face: 'L', index: 8 }],
			[{ face: 'L', index: 6 }, { face: 'F', index: 6 }],
			[{ face: 'L', index: 7 }, { face: 'F', index: 7 }],
			[{ face: 'L', index: 8 }, { face: 'F', index: 8 }]
		]
	},

	B: {
		clockwise: [
			[{ face: 'B', index: 0 }, { face: 'B', index: 6 }],
			[{ face: 'B', index: 1 }, { face: 'B', index: 3 }],
			[{ face: 'B', index: 2 }, { face: 'B', index: 0 }],
			[{ face: 'B', index: 3 }, { face: 'B', index: 7 }],
			[{ face: 'B', index: 5 }, { face: 'B', index: 1 }],
			[{ face: 'B', index: 6 }, { face: 'B', index: 8 }],
			[{ face: 'B', index: 7 }, { face: 'B', index: 5 }],
			[{ face: 'B', index: 8 }, { face: 'B', index: 2 }],
			[{ face: 'U', index: 0 }, { face: 'L', index: 0 }],
			[{ face: 'U', index: 1 }, { face: 'L', index: 3 }],
			[{ face: 'U', index: 2 }, { face: 'L', index: 6 }],
			[{ face: 'L', index: 0 }, { face: 'D', index: 8 }],
			[{ face: 'L', index: 3 }, { face: 'D', index: 7 }],
			[{ face: 'L', index: 6 }, { face: 'D', index: 6 }],
			[{ face: 'D', index: 6 }, { face: 'R', index: 2 }],
			[{ face: 'D', index: 7 }, { face: 'R', index: 5 }],
			[{ face: 'D', index: 8 }, { face: 'R', index: 8 }],
			[{ face: 'R', index: 2 }, { face: 'U', index: 0 }],
			[{ face: 'R', index: 5 }, { face: 'U', index: 1 }],
			[{ face: 'R', index: 8 }, { face: 'U', index: 2 }]
		],

		counterClockwise: [
			[{ face: 'B', index: 0 }, { face: 'B', index: 2 }],
			[{ face: 'B', index: 1 }, { face: 'B', index: 5 }],
			[{ face: 'B', index: 2 }, { face: 'B', index: 8 }],
			[{ face: 'B', index: 3 }, { face: 'B', index: 1 }],
			[{ face: 'B', index: 5 }, { face: 'B', index: 7 }],
			[{ face: 'B', index: 6 }, { face: 'B', index: 0 }],
			[{ face: 'B', index: 7 }, { face: 'B', index: 3 }],
			[{ face: 'B', index: 8 }, { face: 'B', index: 6 }],
			[{ face: 'U', index: 0 }, { face: 'R', index: 2 }],
			[{ face: 'U', index: 1 }, { face: 'R', index: 5 }],
			[{ face: 'U', index: 2 }, { face: 'R', index: 8 }],
			[{ face: 'R', index: 2 }, { face: 'D', index: 6 }],
			[{ face: 'R', index: 5 }, { face: 'D', index: 7 }],
			[{ face: 'R', index: 8 }, { face: 'D', index: 8 }],
			[{ face: 'D', index: 6 }, { face: 'L', index: 6 }],
			[{ face: 'D', index: 7 }, { face: 'L', index: 3 }],
			[{ face: 'D', index: 8 }, { face: 'L', index: 0 }],
			[{ face: 'L', index: 0 }, { face: 'U', index: 0 }],
			[{ face: 'L', index: 3 }, { face: 'U', index: 1 }],
			[{ face: 'L', index: 6 }, { face: 'U', index: 2 }]
		]
	},
	L: {
		clockwise: [
			[{ face: 'L', index: 0 }, { face: 'L', index: 6 }],
			[{ face: 'L', index: 1 }, { face: 'L', index: 3 }],
			[{ face: 'L', index: 2 }, { face: 'L', index: 0 }],
			[{ face: 'L', index: 3 }, { face: 'L', index: 7 }],
			[{ face: 'L', index: 5 }, { face: 'L', index: 1 }],
			[{ face: 'L', index: 6 }, { face: 'L', index: 8 }],
			[{ face: 'L', index: 7 }, { face: 'L', index: 5 }],
			[{ face: 'L', index: 8 }, { face: 'L', index: 2 }],
			[{ face: 'U', index: 0 }, { face: 'B', index: 8 }],
			[{ face: 'U', index: 3 }, { face: 'B', index: 5 }],
			[{ face: 'U', index: 6 }, { face: 'B', index: 2 }],
			[{ face: 'B', index: 2 }, { face: 'D', index: 6 }],
			[{ face: 'B', index: 5 }, { face: 'D', index: 3 }],
			[{ face: 'B', index: 8 }, { face: 'D', index: 0 }],
			[{ face: 'D', index: 0 }, { face: 'F', index: 0 }],
			[{ face: 'D', index: 3 }, { face: 'F', index: 3 }],
			[{ face: 'D', index: 6 }, { face: 'F', index: 6 }],
			[{ face: 'F', index: 0 }, { face: 'U', index: 0 }],
			[{ face: 'F', index: 3 }, { face: 'U', index: 3 }],
			[{ face: 'F', index: 6 }, { face: 'U', index: 6 }]
		],

		counterClockwise: [
			[{ face: 'L', index: 0 }, { face: 'L', index: 2 }],
			[{ face: 'L', index: 1 }, { face: 'L', index: 5 }],
			[{ face: 'L', index: 2 }, { face: 'L', index: 8 }],
			[{ face: 'L', index: 3 }, { face: 'L', index: 1 }],
			[{ face: 'L', index: 5 }, { face: 'L', index: 7 }],
			[{ face: 'L', index: 6 }, { face: 'L', index: 0 }],
			[{ face: 'L', index: 7 }, { face: 'L', index: 3 }],
			[{ face: 'L', index: 8 }, { face: 'L', index: 6 }],
			[{ face: 'U', index: 0 }, { face: 'F', index: 0 }],
			[{ face: 'U', index: 3 }, { face: 'F', index: 3 }],
			[{ face: 'U', index: 6 }, { face: 'F', index: 6 }],
			[{ face: 'F', index: 0 }, { face: 'D', index: 0 }],
			[{ face: 'F', index: 3 }, { face: 'D', index: 3 }],
			[{ face: 'F', index: 6 }, { face: 'D', index: 6 }],
			[{ face: 'D', index: 0 }, { face: 'B', index: 8 }],
			[{ face: 'D', index: 3 }, { face: 'B', index: 5 }],
			[{ face: 'D', index: 6 }, { face: 'B', index: 2 }],
			[{ face: 'B', index: 2 }, { face: 'U', index: 6 }],
			[{ face: 'B', index: 5 }, { face: 'U', index: 3 }],
			[{ face: 'B', index: 8 }, { face: 'U', index: 0 }]
		]
	},
	R: {
		clockwise: [
			[{ face: 'R', index: 0 }, { face: 'R', index: 6 }],
			[{ face: 'R', index: 1 }, { face: 'R', index: 3 }],
			[{ face: 'R', index: 2 }, { face: 'R', index: 0 }],
			[{ face: 'R', index: 3 }, { face: 'R', index: 7 }],
			[{ face: 'R', index: 5 }, { face: 'R', index: 1 }],
			[{ face: 'R', index: 6 }, { face: 'R', index: 8 }],
			[{ face: 'R', index: 7 }, { face: 'R', index: 5 }],
			[{ face: 'R', index: 8 }, { face: 'R', index: 2 }],
			[{ face: 'U', index: 8 }, { face: 'F', index: 8 }],
			[{ face: 'U', index: 5 }, { face: 'F', index: 5 }],
			[{ face: 'U', index: 2 }, { face: 'F', index: 2 }],
			[{ face: 'F', index: 2 }, { face: 'D', index: 2 }],
			[{ face: 'F', index: 5 }, { face: 'D', index: 5 }],
			[{ face: 'F', index: 8 }, { face: 'D', index: 8 }],
			[{ face: 'D', index: 2 }, { face: 'B', index: 6 }],
			[{ face: 'D', index: 5 }, { face: 'B', index: 3 }],
			[{ face: 'D', index: 8 }, { face: 'B', index: 0 }],
			[{ face: 'B', index: 0 }, { face: 'U', index: 8 }],
			[{ face: 'B', index: 3 }, { face: 'U', index: 5 }],
			[{ face: 'B', index: 6 }, { face: 'U', index: 2 }]
		],
		counterClockwise: [
			[{ face: 'R', index: 0 }, { face: 'R', index: 2 }],
			[{ face: 'R', index: 1 }, { face: 'R', index: 5 }],
			[{ face: 'R', index: 2 }, { face: 'R', index: 8 }],
			[{ face: 'R', index: 3 }, { face: 'R', index: 1 }],
			[{ face: 'R', index: 5 }, { face: 'R', index: 7 }],
			[{ face: 'R', index: 6 }, { face: 'R', index: 0 }],
			[{ face: 'R', index: 7 }, { face: 'R', index: 3 }],
			[{ face: 'R', index: 8 }, { face: 'R', index: 6 }],
			[{ face: 'U', index: 8 }, { face: 'B', index: 0 }],
			[{ face: 'U', index: 5 }, { face: 'B', index: 3 }],
			[{ face: 'U', index: 2 }, { face: 'B', index: 6 }],
			[{ face: 'B', index: 0 }, { face: 'D', index: 8 }],
			[{ face: 'B', index: 3 }, { face: 'D', index: 5 }],
			[{ face: 'B', index: 6 }, { face: 'D', index: 2 }],
			[{ face: 'D', index: 2 }, { face: 'F', index: 2 }],
			[{ face: 'D', index: 5 }, { face: 'F', index: 5 }],
			[{ face: 'D', index: 8 }, { face: 'F', index: 8 }],
			[{ face: 'F', index: 2 }, { face: 'U', index: 2 }],
			[{ face: 'F', index: 5 }, { face: 'U', index: 5 }],
			[{ face: 'F', index: 8 }, { face: 'U', index: 8 }]
		]
	}

};